language: php

sudo: false

php:
  - 7.1
  - 7.2

install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer install --prefer-dist

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls

env:
  global:
    - secure: "a831785c473a207fd00614e03065d131"
    - secure: "94b62df41eb655875707b081b3485356"