dist: trusty

language: php

sudo: false

php:
  - 7.1
  - 7.2

env:
 matrix:
    - TEST_SUITE=unit

cache:
  directories:
    - $HOME/.composer/cache

install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer install --prefer-dist

script:
  - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpunit; fi"